idf_component_register(
    SRCS
        "main.c"
        "button_reset.c"
        "barrier/barrier_client.c"
        "barrier/barrier_packet.c"
        "barrier/barrier_io.c"
        "network/eth_network.c"
        "network/tls_client.c"
        "network/reconnect.c"
        "tusb/tusb_device.c"
        "tusb/tusb_actuator.c"
        "tusb/keycodes.c"
        "config/config.c"
        "led/led_rgb.c"
        "usb_host/usb_host_msc.c"
        "web/web_server.c"
        "grove/grove_uart.c"
    PRIV_REQUIRES
        esp-tls
        esp_event
        esp_netif
        esp_eth
        esp_tinyusb
        esp_timer
        esp_driver_gpio
        esp_driver_uart
        esp_driver_ledc
        esp_http_server
        usb
        vfs
        fatfs
    INCLUDE_DIRS
        "."
        "barrier"
        "network"
        "tusb"
        "config"
        "led"
        "usb_host"
        "web"
        "grove"
)
