/*
 * Settings HTML page
 * Served at /
 */
#ifndef SETTINGS_PAGE_H
#define SETTINGS_PAGE_H

static const char SETTINGS_PAGE[] =
"<!DOCTYPE html><html><head>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>deskflow settings</title>"
"<style>"
"body{font-family:system-ui,sans-serif;background:#111;color:#eee;margin:0;padding:16px}"
"form{max-width:400px;margin:0 auto}"
"label{display:block;margin-top:12px;font-size:13px;color:#aaa}"
"input,select{width:100%;padding:8px;margin-top:4px;border:none;border-radius:4px;"
"background:#222;color:#eee;font-size:14px;box-sizing:border-box}"
"button{margin-top:24px;width:100%;padding:12px;border:none;border-radius:6px;"
"background:#0a6;font-size:16px;cursor:pointer}"
"button:hover{background:#0b7}"
"button.danger{background:#a33;margin-top:12px}"
"button.danger:hover{background:#c44}"
"h1{font-size:20px;text-align:center;margin-bottom:8px}"
".row{display:flex;gap:8px}"
".row input{width:50%}"
"</style></head><body>"
"<h1>deskflow client</h1>"
"<form id='f'>"
"<label>Server</label>"
"<input id='server' name='server' required>"
"<label>Port</label>"
"<input id='port' type='number' name='port' required>"
"<label>Device name</label>"
"<input id='device_name' name='device_name'>"
"<label>Screen resolution</label>"
"<div class='row'>"
"<input id='width' type='number' name='screen_width'>"
"<input id='height' type='number' name='screen_height'>"
"</div>"
"<label>Display scaling</label>"
"<select id='scaling' name='scaling'>"
"<option value='100'>100%</option>"
"<option value='125'>125%</option>"
"<option value='150'>150%</option>"
"<option value='200'>200%</option>"
"</select>"
"<label>Jiggle interval (s)</label>"
"<input id='jiggle' type='number' name='jiggle_interval' min='0'>"
"<label><input type='checkbox' id='keep_awake' name='keep_awake' style='width:auto'>"
" Keep display awake</label>"
"<label>Keyboard layout</label>"
"<select id='keyboard_layout' name='keyboard_layout'>"
"<option value='0'>US</option>"
"<option value='1'>German (DE)</option>"
"</select>"
"<label>VLAN ID (-1 = disabled)</label>"
"<input id='vlan_id' type='number' name='vlan_id' min='-1' max='4094'>"
"<button type='submit'>Save</button>"
"<button type='button' class='danger' onclick='reboot()'>Reboot</button>"
"</form>"
"<script>"
"const load=()=>fetch('/api/settings').then(r=>r.json()).then(d=>{"
"document.getElementById('server').value=d.server||'';"
"document.getElementById('port').value=d.port||24800;"
"document.getElementById('device_name').value=d.device_name||'';"
"document.getElementById('width').value=d.screen_width||1920;"
"document.getElementById('height').value=d.screen_height||1080;"
"document.getElementById('scaling').value=d.scaling||100;"
"document.getElementById('jiggle').value=d.jiggle_interval||30;"
"document.getElementById('keep_awake').checked=!!d.keep_awake;"
"document.getElementById('keyboard_layout').value=d.keyboard_layout||0;"
"document.getElementById('vlan_id').value=d.vlan_id ?? -1;"
"});"
"load();"
"document.getElementById('f').onsubmit=async e=>{"
"e.preventDefault();"
"const d={};new FormData(e.target).forEach((v,k)=>d[k]=v);"
"if(d.keep_awake===undefined) d.keep_awake=0; else d.keep_awake=1;"
"d.port=+d.port;d.screen_width=+d.screen_width;d.screen_height=+d.screen_height;"
"d.scaling=+d.scaling;d.jiggle_interval=+d.jiggle_interval;d.keyboard_layout=+d.keyboard_layout;"
"d.vlan_id=+d.vlan_id;"
"fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify(d)});load();"
"};"
"function reboot(){if(confirm('Reboot now?'))fetch('/api/reboot');}"
"</script>"
"<hr><label>Certificates (PEM)</label>"
"<label style='font-size:11px'>CA</label>"
"<textarea id='ca' style='width:100%;height:60px;background:#1a1a1a;color:#ccc;border:1px solid #333;padding:4px;font-size:11px'></textarea>"
"<label style='font-size:11px'>Client cert</label>"
"<textarea id='cert' style='width:100%;height:60px;background:#1a1a1a;color:#ccc;border:1px solid #333;padding:4px;font-size:11px'></textarea>"
"<label style='font-size:11px'>Client key</label>"
"<textarea id='key' style='width:100%;height:60px;background:#1a1a1a;color:#ccc;border:1px solid #333;padding:4px;font-size:11px'></textarea>"
"<button type='button' onclick='uploadCerts()'>Upload certs</button>"
"<script>"
"function uploadCerts(){"
"fetch('/api/cert',{method:'POST',headers:{'Content-Type':'application/json'}"
",body:JSON.stringify({"
"ca:document.getElementById('ca').value,"
"cert:document.getElementById('cert').value,"
"key:document.getElementById('key').value"
"})}).then(r=>{if(r.ok)alert('Certs uploaded. Reconnecting...');else alert('Upload failed');});"
"}"
"</script></body></html>";

#endif
