/*
 * UART terminal HTML page
 * Served at /uart
 */

const char UART_PAGE[] =
"<!DOCTYPE html><html><head>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>UART Terminal</title>"
"<style>"
"body{font-family:system-ui,sans-serif;background:#111;color:#eee;margin:0;padding:16px}"
"#rx{width:100%;height:350px;background:#0a0a0a;color:#0f0;font-family:monospace;"
"font-size:13px;padding:8px;border:1px solid #333;border-radius:4px;"
"overflow-y:auto;white-space:pre-wrap;word-break:break-all;box-sizing:border-box}"
".tx-row{display:flex;gap:8px;margin-top:8px;flex-wrap:wrap}"
".tx-row input{flex:1;min-width:150px;padding:8px;border:none;border-radius:4px;background:#222;color:#eee;font-size:14px}"
".tx-row button{padding:8px 16px;border:none;border-radius:4px;cursor:pointer;color:#fff;font-size:13px}"
".btn-ws{background:#0a6}"
".btn-post{background:#660}"
".btn-read{background:#066}"
"h1{font-size:18px;text-align:center}"
"#status{font-size:12px;color:#888;text-align:center;margin-bottom:8px}"
"</style></head><body>"
"<h1>Grove UART</h1>"
"<div id='status'>disconnected</div>"
"<div id='rx'></div>"
"<div class='tx-row'>"
"<input id='tx' type='text' placeholder='Type to send...'>"
"<button class='btn-ws' onclick='sendWS()'>Send WS</button>"
"<button class='btn-post' onclick='sendPOST()'>Send POST</button>"
"<button class='btn-read' onclick='readPOST()'>Read POST</button>"
"</div>"
"<script>"
"var ws,rx=document.getElementById('rx'),st=document.getElementById('status');"
"function connect(){"
"var p=location.protocol==='https:'?'wss://':'ws://';"
"ws=new WebSocket(p+location.host+'/api/uart/ws');"
"ws.binaryType='arraybuffer';"
"ws.onopen=function(){st.textContent='WS connected';st.style.color='#0f0';};"
"ws.onclose=function(){st.textContent='WS disconnected';st.style.color='#f00';setTimeout(connect,2000);};"
"ws.onmessage=function(e){var b=new Uint8Array(e.data);var s='';"
"for(var i=0;i<b.length;i++)s+=String.fromCharCode(b[i]);"
"rx.textContent+=s;rx.scrollTop=rx.scrollHeight;};"
"}"
"function sendWS(){var t=document.getElementById('tx');if(ws&&ws.readyState===1&&t.value){ws.send(t.value);t.value='';}}"
"function sendPOST(){"
"var t=document.getElementById('tx');if(!t.value)return;"
"fetch('/api/uart/write',{method:'POST',body:t.value}).then(function(){t.value='';}).catch(function(e){rx.textContent+='[send err] '+e+'\\\\n';});"
"}"
"function readPOST(){"
"fetch('/api/uart/read',{method:'POST'}).then(function(r){return r.json();}).then(function(d){"
"var s='';for(var i=0;i<d.bytes.length;i++)s+=String.fromCharCode(d.bytes[i]);"
"if(s){rx.textContent+=s;rx.scrollTop=rx.scrollHeight;}"
"else{rx.textContent+='[no data]\\\\n';rx.scrollTop=rx.scrollHeight;}}"
").catch(function(e){rx.textContent+='[read err] '+e+'\\\\n';});"
"}"
"connect();"
"</script></body></html>";
